dist: bionic
addons:
  snaps:
  - name: google-cloud-sdk
    confinement: classic
  - name: fluxctl
    confinement: classic
  - name: kubectl
    confinement: classic
  - name: vault
    confinement: classic

services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- export PATH=$PATH:/snap/google-cloud-sdk/current/bin
- vault login "${VAULT_TOKEN}"
- vault kv get -field=secret "gcp/gcp-k8s-sa-${PROJECT}" > client-secret.json;
- vault kv get -field=secret "gcp/k8s-deploy-ssh-key" > /tmp/ssh_key
- if [[ "${PROJECT}" == "production" ]]; then export GCP_ZONE="${GCP_ZONE:-us-east1};
  else export GCP_ZONE="${GCP_ZONE:-us-east4}"; 
- gcloud -q auth activate-service-account --key-file ${TRAVIS_BUILD_DIR}/client-secret.json";
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/ssh_key
- ssh-add /tmp/ssh_key
- gcloud -q config set project travis-ci-${PROJECT}-services-1
- gcloud -q config set compute/zone ${GCP_ZONE}
- export GKE_CLUSTER="${GKE_CLUSTER:-travis-ci-services-1}"
- gcloud container clusters get-credentials ${GKE_CLUSTER}
- gcloud auth configure-docker
install: true
jobs:
  include:
  - stage: ":ship: it"
    script: make ship
