dist: bionic
addons:
  snaps:
  - name: google-cloud-sdk
    confinement: classic
  - name: fluxctl
    confinement: classic
  - name: kubectl
    confinement: classic
  - name: vault
    confinement: classic

services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- export PATH=$PATH:/snap/google-cloud-sdk/current/bin
- vault login "${VAULT_TOKEN}"
- vault kv get -field=secret "gcp/gcp-k8s-sa-${PROJECT}" > client-secret.json;
- vault kv get -field=secret "gcp/k8s-deploy-ssh-key" > /tmp/ssh_key
- curl -sLO http://ppa.launchpad.net/rmescandon/yq/ubuntu/pool/main/y/yq/yq_3.1-2_amd64.deb && sudo dpkg -i yq_3.1-2_amd64.deb && rm -f yq_3.1-2_amd64.deb;
- if [[ "${PROJECT}" == "production" ]]; then export GCP_ZONE="${GCP_ZONE:-us-east1}";
  export GKE_CLUSTER="${GKE_CLUSTER:-travis-ci-services}";
  APPS_CLUSTER=$(yq r ./apps.yaml ${DEPLOYMENT_NAME}-${PROJECT}.cluster);
  if [[ "xx${APPS_CLUSTER}" != "xx" ]]; then GKE_CLUSTER=${APPS_CLUSTER}; fi;
  export GCE_PROJECT="travis-ci-prod-services-1";
  else
  export GCP_ZONE="${GCP_ZONE:-us-east4}";
  export GKE_CLUSTER="${GKE_CLUSTER:-travis-ci-services-1}";
  export GCE_PROJECT="travis-ci-staging-services-1"; fi
- gcloud -q auth activate-service-account --key-file "${TRAVIS_BUILD_DIR}/client-secret.json";
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/ssh_key
- ssh-add /tmp/ssh_key
- gcloud -q config set project ${GCE_PROJECT}
- gcloud -q config set compute/zone ${GCP_ZONE}
- gcloud container clusters get-credentials ${GKE_CLUSTER}
- gcloud auth configure-docker
install: true
jobs:
  include:
  - stage: ":ship: it"
    script: 
      - export NOTIFICATION_DATA='{"build_url":"'${TRAVIS_BUILD_WEB_URL}'"}'
      - make ship
      - if [ "$?" -eq "0" ]; then
        curl -k -H "Content-Type: application/json" -X POST -d $NOTIFICATION_DATA https://fluxbot-staging.travis-ci.org/hubot/$PROJECT/$K8S_APP_REPO/$K8S_APP_REPO_COMMIT/success;
        exit 0;
        else
        curl -k -H "Content-Type: application/json" -X POST -d $NOTIFICATION_DATA https://fluxbot-staging.travis-ci.org/hubot/$PROJECT/$K8S_APP_REPO/$K8S_APP_REPO_COMMIT/failed;
        exit 1;
        fi

